### ISSUE TITLE
Stratux software failed to start after upgrade

### ISSUE THREAD

**Issue by cpignol** [jpoirier/stratux-setup#42]
I have a Raspberry PI3 and Jessie light. 
uname -a Linux raspberrypi 4.9.24-v7+ #993 SMP Wed Apr 26 18:01:23 BST 2017
I use stratux-setup for the installation and the updates. Everything was working fine. 
Try to update the stratux software today by running 
cd /root/stratux-setup  
git pull
bash stratux-setup.sh
After the reboot, the stratux process don't start.

From the syslog

May 24 04:28:19 raspberrypi systemd[1]: Starting Stratux...
May 24 04:28:19 raspberrypi systemd[1]: Started Stratux.
May 24 04:28:19 raspberrypi gen_gdl90[4296]: 2017/05/24 04:28:19 Stratux ahrs0.5.1 (bc54533351d03c34ad5eb300c422308bbc3a1660) starting.
May 24 04:28:19 raspberrypi gen_gdl90[4296]: 2017/05/24 04:28:19 read in settings.
May 24 04:28:19 raspberrypi gen_gdl90[4296]: 2017/05/24 04:28:19 Entered uatReader() ...
May 24 04:28:19 raspberrypi gen_gdl90[4296]: panic: embd: your host ": ARMv7 Processor rev 4 (v7l)" is not supported at this moment. request support at https://github.com/kidoman/embd/issues
May 24 04:28:19 raspberrypi gen_gdl90[4296]: goroutine 1 [running]:
May 24 04:28:19 raspberrypi gen_gdl90[4296]: panic(0x4d7b80, 0x10ac4078)
May 24 04:28:19 raspberrypi gen_gdl90[4296]: /root/go/src/runtime/panic.go:500 +0x33c
May 24 04:28:19 raspberrypi gen_gdl90[4296]: github.com/kidoman/embd.NewI2CBus(0x10a67e01, 0x0, 0x0)
May 24 04:28:19 raspberrypi gen_gdl90[4296]: /root/go_path/src/github.com/kidoman/embd/i2c.go:75 +0x60
May 24 04:28:19 raspberrypi gen_gdl90[4296]: main.initI2CSensors()
May 24 04:28:19 raspberrypi gen_gdl90[4296]: /root/stratux/main/sensors.go:30 +0x1c
May 24 04:28:19 raspberrypi gen_gdl90[4296]: main.main()
May 24 04:28:19 raspberrypi gen_gdl90[4296]: /root/stratux/main/gen_gdl90.go:1437 +0xb90
May 24 04:28:19 raspberrypi systemd[1]: stratux.service: main process exited, code=exited, status=2/INVALIDARGUMENT
May 24 04:28:19 raspberrypi systemd[1]: Unit stratux.service entered failed state.
May 24 04:28:24 raspberrypi systemd[1]: stratux.service holdoff time over, scheduling restart.
May 24 04:28:24 raspberrypi systemd[1]: Stopping Stratux...

Any idea what went wrong?
Thanks

**Comment by Snowflake6** [comment]
I have this problem as well.

Stratux 1.2.r2, uname -a gives:
Linux raspberrypi 4.9.35-v7+ #1014 SMP Fri Jun 30 14:47:43 BST 2017 armv7l GNU/Linux

It was running fine this AM, then I did a sudo apt-get upgrade and it went into the state above.  I'll have to try rolling back to a fresh burn of 1.2r2 and see if that fixes it.
